### ISSUE TITLE
Doesn't handle negative values

### ISSUE THREAD

**Issue by inorganik** [MAKIO135/console.chart#2]
I noticed that the chart looks all funky if there are negative values mixed in. Example: 

    console.chart([4,7,3,-5,-9,3,-6,2])

**Comment by MAKIO135** [comment]
This is relative to #3, lines are misaligned because negative values are in this case longer (2 characters) than positive values (1 character). The error comes from line 26 of console.chart.js ( https://github.com/MAKIO135/console.chart/blob/master/console.chart.js#L26 ):
```let len = ( '' + params.max ).length;```
the number of white spaces i based on the biggest value in data, while it should check for the longest string representation of the data.
